apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.exporter.service.app.name }} 
  labels:
    group: {{ .Values.exporter.group }}
    app:  {{ .Values.exporter.name }}
spec:
  type: {{ .Values.exporter.service.app.type }}
  ports:
    - name: {{ .Values.exporter.service.app.http.name }}
      port: {{ .Values.exporter.service.app.http.port }}
      targetPort: {{ .Values.exporter.service.app.http.targetPort }}
      protocol: {{ .Values.exporter.service.app.http.portType }}
      {{- if eq .Values.exporter.service.app.type "NodePort" }}
      nodePort: {{ .Values.exporter.service.app.http.nodePort }}
      {{- end }}    
  selector:
    app: {{ .Values.exporter.name }}